### PR TITLE
remove unmaintained projects [WIP]. Issue#123

### PR DESCRIPTION
**Pull request by makkoncept**
hi @lk-geimfari , I have created a simple python [script](https://gist.github.com/makkoncept/a4761815c67dfca5e6f109c11a9564bd) to automate the #123.
I have pushed the changes in javascript.md, for you to review. Will push others after getting a green flag.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@makkoncept Hi! I really like this script! How about adding Travis CI with automatically checking of last commit date and when last commit date was greater than 9 month ago we will raise error. Do you interested?

**Comment by lk-geimfari** [comment]
@makkoncept If you don't want to work on it, can i use your script?

**Comment by makkoncept** [comment]
@lk-geimfari I should point out that while the script reduces human labour significantly, it is not full proof.
for example, it only checks the master branch for the last commit date. If you want to check for all the branches, you may run out of the request limit, as some projects have many branches present. Therefore a small minority of projects are left out, which may be doing development in a different branch say `dev` and have not pushed code to the master branch for over 9 months.

**Comment by makkoncept** [comment]
@lk-geimfari  i am naive to Travis Cl, so you can use the script. It would be great if it can help make this project better. 
So would I continue pushing to this PR?

**Comment by lk-geimfari** [comment]
@makkoncept Sure! Let me know when you finish with this PR.

**Comment by makkoncept** [comment]
@lk-geimfari  I have pushed the changes, you can review them.
Also the [RUBY.md](https://github.com/lk-geimfari/awesomo/blob/master/languages/RUBY.md) file of the repository had the same content over and over. maybe someone committed it by mistake. It was also resolved in the PR

**Comment by makkoncept** [comment]
@lk-geimfari  a gentle ping

**Comment by lk-geimfari** [comment]
@makkoncept I missed your message in notifications. I'll merge this PR.

Do you interested to be of our maintainer?

**Comment by makkoncept** [comment]
Hi @lk-geimfari , I am very excited by your offer. I have dropped you a mail regarding this

**Comment by lk-geimfari** [comment]
@makkoncept Great! Thank you! Check your email too, please.

**Pull request merged**
