### PR TITLE
Remove iris

### PR DESCRIPTION
**Pull request by dlsniper**
Hello,

I'd like to ask you to remove iris project from the list. This is based on previous experience with the author https://github.com/avelino/awesome-go/pull/1135 and now a problem that I'd rather not disclose in public. I'd be happy to clarify if needed.

Thank you and sorry to drag you into this.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@dlsniper We immediately delete this shit from list. Thanks.

**Comment by dlsniper** [comment]
Please, there's no reason to use this language. Maybe someday the author will own his mistake and we can all move on. Thank you for your quick reply.

**Comment by lk-geimfari** [comment]
@dlsniper Of course, you're right. I've been too hasty. I'm sorry.

**Comment by lk-geimfari** [comment]
@dlsniper If you don't mind, I'll close this discussion.

**Comment by dlsniper** [comment]
Sure, up to you :) Btw, thanks for the repo, it's really cool!

**Comment by lk-geimfari** [comment]
Guys, if something change with `Iris` let us know, please.

**Pull request merged**
