### PR TITLE
Please add openVALIDATION to this awesome list of open source projects

### PR DESCRIPTION
**Pull request by thecodemonkey**
OpenVALIDATION enables you to generate validation rules from natural language-like expressions in English and German without any knowledge in programming. The validation rules can be automatically translated by openVALIDATION into Java, JavaScript or C#, with more languages to come!

openVALIDATION

## schema
```json
{
    "weather": "string"
}
```

## rule
```
The weather must be rainy.
```

## cli call
```batch
java -jar openvalidation.jar /
       --culture en /
       --language javascript /
       --rule "The weather must be rainy." /
       --schema "{ weather: string }" /
       --output code.js
```

## will result in
```javascript
if(model.getWeather() != "rainy")
{
    throw new Exception("The weather must be rainy.");
}
```

------

I've added another category called "Natural Language". openVALIDATION is written in Java, but the use of a natural language is in the foreground. I thought it might also be of interest for your overview.

If you don't like "Natural Language" as an additional category, then leave the category out and just take over the entry in Java.md

We'd like to hear from you.
Ilja (openVALIDATION)

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@thecodemonkey Please, add it to list `JAVA.md`/

**Comment by thecodemonkey** [comment]
Ok, I've adjusted that now. Only the file Java.md now contains a new entry.

**Comment by lk-geimfari** [comment]
@thecodemonkey Thank ya!

**Comment by thecodemonkey** [comment]
balshoje spasibo. thanks a lot!

**Pull request merged**
