### PR TITLE
Add SweetAlert, Video.js, Ace, Dragula, Hyper, Docsify, WebTorrent & PhotoSwipe

### PR DESCRIPTION
**Pull request by deadcoder0904**
Yo, add this too. It ain't Mammoth's Shit :joy:

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@deadcoder0904 Please, use following format

```
[**some project**](link) - desccription
![screen]()

---
[**some project2**](link) - desccription2
![screen2]()
```

**Comment by lk-geimfari** [comment]
@deadcoder0904 Fix it and i will merge this PR.

**Comment by deadcoder0904** [comment]
On it

**Comment by lk-geimfari** [comment]
@deadcoder0904 Thank you!

**Comment by deadcoder0904** [comment]
Hey @lk-geimfari, I've used the same format. Some projects like Video.js can't literally add there screenshots. Can u tell me specifically what to remove ? Is the Official Site link is what to remove or Features ?

**Comment by lk-geimfari** [comment]
@deadcoder0904 Yeah, of course!

**Comment by deadcoder0904** [comment]
Done :+1: 
Please check it.

**Comment by lk-geimfari** [comment]
@deadcoder0904 Nice job!

**Pull request merged**
