### PR TITLE
Add Riak KV/TS to erlang

### PR DESCRIPTION
**Pull request by gpad**
Add Riak KV/TS to erlang languages

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@gpad Thanks!

**Comment by gpad** [comment]
There is a problem on image related to riak, giveme 1 min to fix it, sorry.

**Comment by gpad** [comment]
I create the new pull request to fix the problem, sorry.

**Comment by lk-geimfari** [comment]
@gpad It's not a problem. Thank you!

**Pull request merged**
