### PR TITLE
Adding NODEJS.md

### PR DESCRIPTION
**Pull request by deadcoder0904**

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@deadcoder0904 Can you merge it yourself?

**Comment by deadcoder0904** [comment]
@lk-geimfari Some projects like `N1` are actually `NODE_JS` Projects.... So what do u think about moving all the Projects to only `JAVASCRIPT.md` or to keep 2 separate files `JAVASCRIPT.md` & `NODEJS.md`

**Comment by deadcoder0904** [comment]
Yes I can

**Comment by lk-geimfari** [comment]
@deadcoder0904 No problem. You can do it without my permission. You are moderator of Node, JS an CSS lists.

**Pull request merged**
