### PR TITLE
Update GOLANG.md

### PR DESCRIPTION
**Pull request by TrueFurby**
- added centered title for each project
- fixed some formatting issues

---
To simplify my work I replaced it using following regular expressions: 

Finds all horizontal lines ("---") followed by project link and all used forms of dash/spacing after it
`\n\n*---\n\[\*\*\s*(.+)\s*\*\*\s*\]\((\S+)\)\s+[\—\-]*\s*` 

Replaces it with centered title and unifies dash after link (to "—")
`\n\n## <div align="center">\1</div>\n\n[**\1**](\2) — `

Might come useful for anyone who wants to do the same.  #69 

Going to center those images too now.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@TrueFurby :+1:

**Comment by TrueFurby** [comment]
Center all images using:

**Find:** `\!\[.*\]\((\S+)\)`
**Replace:** `<p align="center"></p>`

**Comment by lk-geimfari** [comment]
@TrueFurby Can you update other list like list for GO?

**Comment by TrueFurby** [comment]
Sure, but I'm busy today. I'll do later.

**Comment by lk-geimfari** [comment]
@TrueFurby Of course. Only when you will have free time.

**Pull request merged**
