### PR TITLE
Add World War of Ants to the Java list

### PR DESCRIPTION
**Pull request by JeffUTF8**

### CODE REVIEW

**Comment by lk-geimfari** [comment]
We need more info and good README to merge it. Please, update README.

**Comment by JeffUTF8** [comment]
Unfortunately I'm not the maintainer. Looks like we'll have to stall this for a little while

**Comment by JeffUTF8** [comment]
@lk-geimfari we've just updated the README. Is the current one good enough? https://github.com/warofants/wwa/blob/master/README.md

**Comment by lk-geimfari** [comment]
@JeffUTF8 Much better!

**Pull request merged**
