### PR TITLE
Add Qt to the C++ list

### PR DESCRIPTION
**Pull request by jcelerier**
It's the major cross-platform lib for GUIs with C++.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@jcelerier Can you add link to github repository? Where hosted repository of `Qt` ?

**Comment by jcelerier** [comment]
it's hosted at https://github.com/qt ; should I make another commit that you will squash ?

**Comment by lk-geimfari** [comment]
@jcelerier It's done!

**Comment by jcelerier** [comment]
nice, thanks :) good job with the project :)

**Pull request merged**
