### PR TITLE
Add Monique Dashboards to PYTHON.md

### PR DESCRIPTION
**Pull request by aartur**
Added [Monique Dashboards](https://github.com/monique-dashboards/monique) which is an innovative library for creating custom dashboards.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
Can you create this PR again, please? All new projects should be added in end of file.

**Comment by lk-geimfari** [comment]
I'll reformat file alphabetically in future, but at this moment we use this format.

**Comment by aartur** [comment]
Ok, I wasn't sure what is the intended order.

**Comment by lk-geimfari** [comment]
@aartur Sorry for that. I'll change structure of the file as soon as possible.

**Pull request merged**
