### PR TITLE
Added AREG SDK to the C++ list.

### PR DESCRIPTION
**Pull request by aregtech**
It is definitely not a dead project, it is new and has room to grow. It offers a solution of the relatively new IoT paradigm called "mist computing". It is cross-platform, suitable for embedded and high-end systems.

### CODE REVIEW

**Comment by aregtech** [comment]
@lk-geimfari, thank you for merging. But I've checked the [C++.md](https://github.com/lk-geimfari/awesomo/blob/master/languages/C%2B%2B.md) file and didn't find there the updates. Was there a problem?

**Comment by lk-geimfari** [comment]
> @lk-geimfari, thank you for merging. But I've checked the [C++.md](https://github.com/lk-geimfari/awesomo/blob/master/languages/C%2B%2B.md) file and didn't find there the updates. Was there a problem?

I was updating C++ list yesterday, to make list looks better and accidentally removed this new project. That's totally my bad, gonna fix ASAP.

Thank you for noticing!

**Comment by aregtech** [comment]
@lk-geimfari, Thank you! I appreciate that.

**Comment by lk-geimfari** [comment]
Done!

**Pull request merged**
