### PR TITLE
Add Pyduino - Arduino Control using Python program

### PR DESCRIPTION
**Pull request by Muhammadrasul446**

### CODE REVIEW

**Comment by Muhammadrasul446** [comment]
This a Python program to control arduino, written by a 14 y.o. boy, for himself and others!

**Comment by lk-geimfari** [comment]
Cannot be merged, sorry.

**Comment by Muhammadrasul446** [comment]
> Cannot be merged, sorry.

OK! I'll add smth more interesting if i find!

**Comment by lk-geimfari** [comment]
@Muhammadrasul446 Thank you for understanding. We are mostly collecting here popular and common use projects.

**Pull request closed without merging**
