### PR TITLE
Order CLOJURE.md alphabetically

### PR DESCRIPTION
**Pull request by pitalig**
Related to https://github.com/lk-geimfari/awesomo/issues/101

### CODE REVIEW

**Comment by klebervirgilio** [comment]
@pitalig take a look at this https://gist.github.com/klebervirgilio/c8a8bf0a11b489f5fc1911e302e582db might help you.

**Comment by pitalig** [comment]
Done! :smile: 
Thanks @klebervirgilio for the great script! :tada:

**Comment by makkoncept** [comment]
Hi @pitalig , great work. I just want to point out that there may be some projects that are inactive for 9 months or more, for example [cortex](https://github.com/originrose/cortex) can you please remove them. You can refer #123 and #138

**Comment by pitalig** [comment]
@makkoncept cortex removed, seems that this is the only inactive here, thanks for pointing this issue and for the python script!

**Pull request merged**
