### PR TITLE
Added Maven

### PR DESCRIPTION
**Pull request by MladenZeljic**
Added Maven to java project list

### CODE REVIEW

**Comment by MladenZeljic** [comment]
@lk-geimfari

**Comment by lk-geimfari** [comment]
Everyone who works with Java knows about Maven. We don't such tools here.

**Comment by MladenZeljic** [comment]
@lk-geimfari Well you should have mentioned that they have to be lesser known projects.

**Comment by lk-geimfari** [comment]
@MladenZeljic Please, don't get me wrong. Maven is a great project and it's very important for the Java ecosystem, but it's a most common tool, like `pip` in Python-world. It's hard to find Java developer/enthusiast who doesn't know about Maven.

**Pull request closed without merging**
