### PR TITLE
Add 23 projects to C#

### PR DESCRIPTION
**Pull request by Diamed**

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@Diamed Oh, cool! Tell me, please, do you checked [activity](https://github.com/lk-geimfari/awesomo/blob/master/CONTRIBUTING.md#guidelines) of all these projects?

**Comment by Diamed** [comment]
@lk-geimfari yes, i check activity on all of this repositories

**Comment by lk-geimfari** [comment]
@Diamed I sent invite for you. Now you're collaborator. You can merge PR by yourself.

**Comment by Diamed** [comment]
@lk-geimfari Thank you very much!

**Pull request merged**
